#ifndef KEYSHARP_DESKTOP_PERMISSION_DOMAIN_H
#define KEYSHARP_DESKTOP_PERMISSION_DOMAIN_H

#include <keysharp_permissions/permissions.h>

#define KSD_DESKTOP_MANAGED_SCOPES \
    (KSP_SCOPE_INPUT_CONTROL | KSP_SCOPE_WINDOW_MONITORING \
     | KSP_SCOPE_WINDOW_CONTROL \
     | KSP_SCOPE_SCREEN_CAPTURE | KSP_SCOPE_AUDIO_CAPTURE \
     | KSP_SCOPE_CAMERA_CAPTURE | KSP_SCOPE_CLIPBOARD_MONITORING)

#define KSD_DESKTOP_ACCEPTED_SCOPES KSD_DESKTOP_MANAGED_SCOPES

#endif
