#ifndef KEYSHARP_DESKTOP_PROTOCOL_H
#define KEYSHARP_DESKTOP_PROTOCOL_H

#include "keysharp_desktop/client.h"

#define KSD_PRODUCT_NAME "keysharp-desktop"
#define KSD_PRODUCT_VERSION "0.2.0"

#define KSD_CLIENT_PROTOCOL_NAME "keysharp-desktop/client"
#define KSD_PROTOCOL_MAJOR 2u
#define KSD_PROTOCOL_MINOR 0u

#define KSD_FRAME_HEADER_SIZE 24u
#define KSD_FRAME_MAGIC_OFFSET 0u
#define KSD_FRAME_MAJOR_OFFSET 4u
#define KSD_FRAME_MINOR_OFFSET 6u
#define KSD_FRAME_OPCODE_OFFSET 8u
#define KSD_FRAME_FLAGS_OFFSET 10u
#define KSD_FRAME_PAYLOAD_LENGTH_OFFSET 12u
#define KSD_FRAME_REQUEST_ID_OFFSET 16u

#define KSD_FRAME_MAGIC_0 ((uint8_t)'K')
#define KSD_FRAME_MAGIC_1 ((uint8_t)'S')
#define KSD_FRAME_MAGIC_2 ((uint8_t)'D')
#define KSD_FRAME_MAGIC_3 ((uint8_t)'P')

#define KSD_FLAG_RESPONSE 0x0001u
#define KSD_FLAG_EVENT 0x0002u
#define KSD_FLAG_MORE 0x0004u
#define KSD_FLAG_ALL (KSD_FLAG_RESPONSE | KSD_FLAG_EVENT | KSD_FLAG_MORE)

#define KSD_OP_HELLO 0x0001u
#define KSD_OP_AUTHORIZE 0x0002u
#define KSD_OP_PING 0x0003u
#define KSD_OP_PERMISSIONS_LIST 0x0004u
#define KSD_OP_PERMISSIONS_REVOKE 0x0005u
#define KSD_OP_SESSION_REVOKED 0x0006u

#define KSD_OP_CAPTURE_AREA 0x2000u
#define KSD_OP_CAPTURE_WINDOW 0x2001u
#define KSD_OP_WINDOW_LIST 0x2010u
#define KSD_OP_WINDOW_ACTIVE 0x2011u
#define KSD_OP_WINDOW_WATCH 0x2012u
#define KSD_OP_WINDOW_FOCUS 0x2020u
#define KSD_OP_WINDOW_RAISE 0x2021u
#define KSD_OP_WINDOW_LOWER 0x2022u
#define KSD_OP_WINDOW_CLOSE 0x2023u
#define KSD_OP_WINDOW_KILL 0x2024u
#define KSD_OP_WINDOW_MOVE_RESIZE 0x2025u
#define KSD_OP_WINDOW_MOVE_RESIZE_XID 0x2026u
#define KSD_OP_WINDOW_SET_STATE 0x2027u
#define KSD_OP_WINDOW_SET_OPACITY 0x2028u
#define KSD_OP_WINDOW_SET_ABOVE 0x2029u
#define KSD_OP_WINDOW_SET_DECORATED 0x202au
#define KSD_OP_WINDOW_RESERVE 0x202bu
#define KSD_OP_WINDOW_GET_RESERVED 0x202cu
#define KSD_OP_CLIPBOARD_MIMETYPES 0x2030u
#define KSD_OP_CLIPBOARD_CONTENT 0x2031u
#define KSD_OP_CLIPBOARD_TEXT 0x2032u
#define KSD_OP_CLIPBOARD_WATCH 0x2033u
#define KSD_OP_MOUSE_MOVE_ABSOLUTE 0x2040u
#define KSD_OP_MOUSE_MOVE_RELATIVE 0x2041u
#define KSD_OP_MOUSE_BUTTON 0x2042u
#define KSD_OP_MOUSE_SCROLL 0x2043u
#define KSD_OP_CURSOR_POSITION 0x2050u
#define KSD_OP_WORK_AREA 0x2051u
#define KSD_OP_CLIPBOARD_SET_CONTENT 0x2060u
#define KSD_OP_WINDOW_EVENT 0x2110u
#define KSD_OP_CLIPBOARD_EVENT 0x2130u

#define KSD_CAPTURE_WINDOW_INCLUDE_DECORATION 0x00000001u

#define KSD_MAX_REQUEST_PAYLOAD (4u * 1024u)
#define KSD_MAX_REQUEST_TOTAL_PAYLOAD (4u * 1024u * 1024u)
#define KSD_MAX_TEXT_BYTES (4u * 1024u * 1024u)
#define KSD_MAX_CAPTURE_BYTES (256u * 1024u * 1024u)
#define KSD_MAX_CAPTURE_TAIL (KSD_MAX_CAPTURE_BYTES + 20u)
#define KSD_MAX_CAPTURE_DIMENSION 32768u
#define KSD_MAX_CAPTURE_PIXELS (64u * 1024u * 1024u)
#define KSD_MAX_MIMETYPE_BYTES 1024u
#define KSD_MAX_MIMETYPES 4096u
#define KSD_MAX_CLIPBOARD_WRITE_BYTES \
    (KSD_MAX_REQUEST_TOTAL_PAYLOAD - KSD_MAX_MIMETYPE_BYTES - 8u)
#define KSD_MAX_MOUSE_SCROLL_DELTA 12000

#define KSD_PERMISSION_STORE_VERSION "1"

#endif
